name: alpaca_markets
description: A wrapper for the Alpaca Markets broker, trading, and market data APIs.
version: 0.0.1
repository: https://github.com/voidari/flutter-alpaca-markets
issue_tracker: https://github.com/voidari/flutter-alpaca-markets/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
